/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import dados.ListaProjeto;
import dados.ListaReceita;
import dados.ListaUsuario;
import dados.Projeto;
import dados.Receita;
import dados.Usuario;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows 11
 */
public class CadastroProjeto extends javax.swing.JFrame {
  
  
  
  
   
  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroProjeto.class.getName());

  /**
   * Creates new form CadastroProjeto
   */
  public CadastroProjeto() {
    initComponents();
    preencheComboUsuario();
    preencheComboReceita();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
   * Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    txtNome = new javax.swing.JTextField();
    txtMaterial = new javax.swing.JTextField();
    txtDetalhes = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    btnCadastrar = new javax.swing.JButton();
    cmbStatus = new javax.swing.JComboBox<>();
    jLabel8 = new javax.swing.JLabel();
    ftxtDuracao = new javax.swing.JFormattedTextField();
    txtCategoria = new javax.swing.JTextField();
    cmbUsuario = new javax.swing.JComboBox<>();
    jLabel9 = new javax.swing.JLabel();
    cmbReceita = new javax.swing.JComboBox<>();
    jLabel10 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jLabel1.setBackground(new java.awt.Color(204, 204, 204));
    jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 51, 51));
    jLabel1.setText("entre laços & nós");

    jPanel1.setBackground(new java.awt.Color(0, 51, 51));
    jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 2, true));
    jPanel1.setForeground(new java.awt.Color(0, 51, 51));

    jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 20)); // NOI18N
    jLabel2.setText("novo projeto");

    txtNome.setBackground(new java.awt.Color(204, 204, 204));
    txtNome.setForeground(new java.awt.Color(40, 40, 40));

    txtMaterial.setBackground(new java.awt.Color(204, 204, 204));
    txtMaterial.setForeground(new java.awt.Color(40, 40, 40));
    txtMaterial.setNextFocusableComponent(txtDetalhes);

    txtDetalhes.setBackground(new java.awt.Color(204, 204, 204));
    txtDetalhes.setForeground(new java.awt.Color(40, 40, 40));
    txtDetalhes.setNextFocusableComponent(btnCadastrar);

    jLabel3.setBackground(new java.awt.Color(204, 204, 204));
    jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
    jLabel3.setText("nome:");

    jLabel4.setBackground(new java.awt.Color(204, 204, 204));
    jLabel4.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
    jLabel4.setText("categoria:");
    jLabel4.setToolTipText("");

    jLabel5.setBackground(new java.awt.Color(204, 204, 204));
    jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
    jLabel5.setText("duração:");

    jLabel6.setBackground(new java.awt.Color(204, 204, 204));
    jLabel6.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
    jLabel6.setText("status:");

    jLabel7.setBackground(new java.awt.Color(204, 204, 204));
    jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
    jLabel7.setText("material:");

    btnCadastrar.setBackground(new java.awt.Color(204, 204, 204));
    btnCadastrar.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
    btnCadastrar.setForeground(new java.awt.Color(0, 51, 51));
    btnCadastrar.setText("cadastar");
    btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCadastrarActionPerformed(evt);
      }
    });

    cmbStatus.setBackground(new java.awt.Color(204, 204, 204));
    cmbStatus.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
    cmbStatus.setForeground(new java.awt.Color(40, 40, 40));
    cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "em andamento", "finalizado", "dropado" }));
    cmbStatus.setNextFocusableComponent(ftxtDuracao);

    jLabel8.setBackground(new java.awt.Color(204, 204, 204));
    jLabel8.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
    jLabel8.setText("detalhes:");

    ftxtDuracao.setBackground(new java.awt.Color(204, 204, 204));
    ftxtDuracao.setForeground(new java.awt.Color(40, 40, 40));
    try {
      ftxtDuracao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
    } catch (java.text.ParseException ex) {
      ex.printStackTrace();
    }
    ftxtDuracao.setNextFocusableComponent(txtMaterial);

    txtCategoria.setBackground(new java.awt.Color(204, 204, 204));
    txtCategoria.setForeground(new java.awt.Color(40, 40, 40));
    txtCategoria.setNextFocusableComponent(txtDetalhes);

    cmbUsuario.setBackground(new java.awt.Color(204, 204, 204));
    cmbUsuario.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
    cmbUsuario.setForeground(new java.awt.Color(40, 40, 40));
    cmbUsuario.setNextFocusableComponent(ftxtDuracao);

    jLabel9.setBackground(new java.awt.Color(204, 204, 204));
    jLabel9.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
    jLabel9.setText("usuário:");
    jLabel9.setToolTipText("");

    cmbReceita.setBackground(new java.awt.Color(204, 204, 204));
    cmbReceita.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
    cmbReceita.setForeground(new java.awt.Color(40, 40, 40));
    cmbReceita.setNextFocusableComponent(ftxtDuracao);

    jLabel10.setBackground(new java.awt.Color(204, 204, 204));
    jLabel10.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
    jLabel10.setText("id da receita:");
    jLabel10.setToolTipText("");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(16, 16, 16)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel3)
              .addComponent(jLabel8))
            .addGap(0, 0, Short.MAX_VALUE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jLabel4)
              .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jLabel5)
                    .addGap(124, 124, 124))
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel6)
                  .addComponent(jLabel7)
                  .addComponent(cmbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(txtDetalhes)
                .addGroup(jPanel1Layout.createSequentialGroup()
                  .addComponent(ftxtDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel10)
                  .addComponent(cmbReceita, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(12, 12, 12))))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(135, 135, 135)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel2)
          .addComponent(btnCadastrar))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel4)
          .addComponent(jLabel6))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel7)
          .addComponent(jLabel5))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(ftxtDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel8)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel9)
          .addComponent(jLabel10))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cmbReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(btnCadastrar)
        .addGap(64, 64, 64))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1))
          .addGroup(layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(30, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(20, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
    try{
      
      if (txtNome.getText().isEmpty() ||txtCategoria.getText().isEmpty() ||ftxtDuracao.getText().trim().isEmpty() || cmbStatus.getSelectedItem() == null ||
       txtMaterial.getText().isEmpty() || txtDetalhes.getText().isEmpty() || cmbUsuario.getSelectedItem() == null ||cmbReceita.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "preencha todos os campos. crie pelo menos uma receita antes de criar um nov projeto.");
        return;
      }
      
      Projeto novoProjeto = new Projeto();
      
      novoProjeto.setNome(txtNome.getText());
      novoProjeto.setCategoria(txtCategoria.getText());
      novoProjeto.setStatus(cmbStatus.getSelectedItem().toString());
      novoProjeto.setMaterial(txtMaterial.getText());
      novoProjeto.setDetalhes(txtDetalhes.getText());
      Usuario usuarioSelecionado = (Usuario) cmbUsuario.getSelectedItem();
      novoProjeto.setUsuario(usuarioSelecionado);
      Receita receitaSelecionada = (Receita) cmbReceita.getSelectedItem();
      novoProjeto.setReceita(receitaSelecionada);
      
      LocalTime duracao;
      try {
        duracao = LocalTime.parse(ftxtDuracao.getText(),DateTimeFormatter.ofPattern("HH:mm:ss"));
      }
      catch (Exception e) {
        JOptionPane.showMessageDialog(this, "duração inválida!\n ex: (01:20:50)");
        return;
      }
      novoProjeto.setDuracao(duracao);
      
      ListaProjeto listaProjeto = new ListaProjeto();
      listaProjeto.cadastrar(novoProjeto);
      JOptionPane.showMessageDialog(this, "projeto cadastrado com sucesso!" );
      this.dispose();
    }
    catch(Exception e){
      JOptionPane.showMessageDialog(this, "ocorreu uma falha:\n" + e.getMessage());
    }
  }//GEN-LAST:event_btnCadastrarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new CadastroProjeto().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCadastrar;
  private javax.swing.JComboBox<Receita> cmbReceita;
  private javax.swing.JComboBox<String> cmbStatus;
  private javax.swing.JComboBox<Usuario> cmbUsuario;
  private javax.swing.JFormattedTextField ftxtDuracao;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JTextField txtCategoria;
  private javax.swing.JTextField txtDetalhes;
  private javax.swing.JTextField txtMaterial;
  private javax.swing.JTextField txtNome;
  // End of variables declaration//GEN-END:variables
 
  
  private void preencheComboUsuario(){
    ListaUsuario listaUsuario = new ListaUsuario();
    List<Usuario> usuarios = listaUsuario.listar();
    
    for(Usuario u : usuarios){
      cmbUsuario.addItem(u);
    }
  }
  
  private void preencheComboReceita(){
    ListaReceita listaReceita = new ListaReceita();
    List<Receita> receitas = listaReceita.listar();
    
    for(Receita r : receitas){
      cmbReceita.addItem(r);
   }
  }
  

}
