/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import dados.ListaReceita;
import dados.ListaUsuario;
import dados.Receita;
import dados.Usuario;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows 11
 */
public class CadastroReceita extends javax.swing.JFrame {
  
  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroReceita.class.getName());

  /**
   * Creates new form CadastroReceita
   */
  public CadastroReceita() {
    initComponents();
    preencheComboUsuario();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
   * Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    txtNome = new javax.swing.JTextField();
    txtMaterial = new javax.swing.JTextField();
    txtConteudo = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    btnCadastrar = new javax.swing.JButton();
    cmbDificuldade = new javax.swing.JComboBox<>();
    jLabel8 = new javax.swing.JLabel();
    txtCategoria = new javax.swing.JTextField();
    cmbUsuario = new javax.swing.JComboBox<>();
    jLabel9 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jLabel1.setBackground(new java.awt.Color(204, 204, 204));
    jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 51, 51));
    jLabel1.setText("entre laços & nós");

    jPanel1.setBackground(new java.awt.Color(0, 51, 51));
    jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 2, true));
    jPanel1.setForeground(new java.awt.Color(0, 51, 51));

    jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 20)); // NOI18N
    jLabel2.setText("nova receita");

    txtNome.setBackground(new java.awt.Color(204, 204, 204));
    txtNome.setForeground(new java.awt.Color(40, 40, 40));

    txtMaterial.setBackground(new java.awt.Color(204, 204, 204));
    txtMaterial.setForeground(new java.awt.Color(40, 40, 40));

    txtConteudo.setBackground(new java.awt.Color(204, 204, 204));
    txtConteudo.setForeground(new java.awt.Color(40, 40, 40));

    jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
    jLabel3.setText("nome:");

    jLabel4.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
    jLabel4.setText("categoria:");
    jLabel4.setToolTipText("");

    jLabel6.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
    jLabel6.setText("dificuldade:");

    jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
    jLabel7.setText("material:");

    btnCadastrar.setBackground(new java.awt.Color(204, 204, 204));
    btnCadastrar.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
    btnCadastrar.setForeground(new java.awt.Color(0, 51, 51));
    btnCadastrar.setText("cadastar");
    btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCadastrarActionPerformed(evt);
      }
    });

    cmbDificuldade.setBackground(new java.awt.Color(204, 204, 204));
    cmbDificuldade.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
    cmbDificuldade.setForeground(new java.awt.Color(40, 40, 40));
    cmbDificuldade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "inicante/fácil", "intermediário/médio", "avançado/díficil" }));

    jLabel8.setFont(new java.awt.Font("Segoe Script", 0, 14)); // NOI18N
    jLabel8.setText("conteúdo:");

    txtCategoria.setBackground(new java.awt.Color(204, 204, 204));
    txtCategoria.setForeground(new java.awt.Color(40, 40, 40));

    cmbUsuario.setBackground(new java.awt.Color(204, 204, 204));
    cmbUsuario.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
    cmbUsuario.setForeground(new java.awt.Color(40, 40, 40));

    jLabel9.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
    jLabel9.setText("usuário");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(16, 16, 16)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addComponent(txtConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(txtMaterial, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(txtNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addComponent(txtCategoria, javax.swing.GroupLayout.Alignment.LEADING)))
            .addContainerGap(16, Short.MAX_VALUE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jLabel7)
              .addComponent(jLabel3)
              .addComponent(jLabel8)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(cmbDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel9)
                  .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(0, 0, Short.MAX_VALUE))))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(135, 135, 135)
            .addComponent(jLabel2))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(136, 136, 136)
            .addComponent(btnCadastrar)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel7)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel8)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtConteudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel6)
          .addComponent(jLabel9))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(cmbDificuldade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(cmbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(btnCadastrar)
        .addContainerGap(25, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1)))
        .addContainerGap(30, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(20, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
   try{
     
     if (txtNome.getText().isEmpty() ||txtCategoria.getText().isEmpty() ||txtMaterial.getText().isEmpty() || txtConteudo.getText().isEmpty() ||cmbUsuario.getSelectedItem() == null ||cmbDificuldade.getSelectedItem() == null) {
       JOptionPane.showMessageDialog(this, "preencha todos os campos!");
       return;
     }
     
      Receita novaReceita = new Receita();
      
      novaReceita.setNome(txtNome.getText());
      novaReceita.setCategoria(txtCategoria.getText());
      novaReceita.setMaterial(txtMaterial.getText());
      novaReceita.setConteudo(txtConteudo.getText());
      novaReceita.setDificuldade(cmbDificuldade.getSelectedItem().toString());
      Usuario usuarioSelecionado = (Usuario) cmbUsuario.getSelectedItem();
      novaReceita.setUsuario(usuarioSelecionado);
      
      ListaReceita listaReceita = new ListaReceita();
      listaReceita.cadastrar(novaReceita);
      JOptionPane.showMessageDialog(this, "receita cadastrada com sucesso!" );
      this.dispose();
    }
    catch(Exception e){
      JOptionPane.showMessageDialog(this, "ocorreu uma falha:\n" + e.getMessage());
    }
  }//GEN-LAST:event_btnCadastrarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new CadastroReceita().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCadastrar;
  private javax.swing.JComboBox<String> cmbDificuldade;
  private javax.swing.JComboBox<Usuario> cmbUsuario;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JTextField txtCategoria;
  private javax.swing.JTextField txtConteudo;
  private javax.swing.JTextField txtMaterial;
  private javax.swing.JTextField txtNome;
  // End of variables declaration//GEN-END:variables
 
  private void preencheComboUsuario(){
    ListaUsuario listaUsuario = new ListaUsuario();
    List<Usuario> usuarios = listaUsuario.listar();
    
    for(Usuario u : usuarios){
      cmbUsuario.addItem(u);
    }
  }
}
