/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import dados.Criptografia;
import dados.ListaUsuario;
import dados.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows 11
 */
public class CadastroUsuario extends javax.swing.JFrame {
  
  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CadastroUsuario.class.getName());

  /**
   * Creates new form CadastroUsuario
   */
  public CadastroUsuario() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
   * Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    txtNome = new javax.swing.JTextField();
    txtUsername = new javax.swing.JTextField();
    txtEmail = new javax.swing.JTextField();
    txtBiografia = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    btnCadastrar = new javax.swing.JButton();
    jLabel8 = new javax.swing.JLabel();
    cmbTipoUsuario = new javax.swing.JComboBox<>();
    txtSenha = new javax.swing.JPasswordField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jLabel1.setBackground(new java.awt.Color(204, 204, 204));
    jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 51, 51));
    jLabel1.setText("entre laços & nós");

    jPanel1.setBackground(new java.awt.Color(0, 51, 51));
    jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 2, true));
    jPanel1.setForeground(new java.awt.Color(0, 51, 51));

    jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 20)); // NOI18N
    jLabel2.setText("crie sua conta");

    txtNome.setBackground(new java.awt.Color(204, 204, 204));
    txtNome.setForeground(new java.awt.Color(0, 51, 51));
    txtNome.setNextFocusableComponent(txtUsername);

    txtUsername.setBackground(new java.awt.Color(204, 204, 204));
    txtUsername.setForeground(new java.awt.Color(0, 51, 51));
    txtUsername.setNextFocusableComponent(txtEmail);

    txtEmail.setBackground(new java.awt.Color(204, 204, 204));
    txtEmail.setForeground(new java.awt.Color(0, 51, 51));
    txtEmail.setNextFocusableComponent(txtSenha);

    txtBiografia.setBackground(new java.awt.Color(204, 204, 204));
    txtBiografia.setForeground(new java.awt.Color(0, 51, 51));
    txtBiografia.setNextFocusableComponent(btnCadastrar);

    jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
    jLabel3.setText("nome:");

    jLabel4.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
    jLabel4.setText("username:");
    jLabel4.setToolTipText("");

    jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
    jLabel5.setText("email:");

    jLabel6.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
    jLabel6.setText("senha:");

    jLabel7.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
    jLabel7.setText("biografia:");

    btnCadastrar.setBackground(new java.awt.Color(204, 204, 204));
    btnCadastrar.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
    btnCadastrar.setForeground(new java.awt.Color(0, 51, 51));
    btnCadastrar.setText("cadastar");
    btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCadastrarActionPerformed(evt);
      }
    });

    jLabel8.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
    jLabel8.setText("tipo de usuário:");

    cmbTipoUsuario.setBackground(new java.awt.Color(204, 204, 204));
    cmbTipoUsuario.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
    cmbTipoUsuario.setForeground(new java.awt.Color(40, 40, 40));
    cmbTipoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "visitante", "usuário", "admin", " ", " " }));

    txtSenha.setBackground(new java.awt.Color(204, 204, 204));
    txtSenha.setForeground(new java.awt.Color(0, 51, 51));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(146, Short.MAX_VALUE)
        .addComponent(jLabel2)
        .addGap(147, 147, 147))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(150, 150, 150)
            .addComponent(btnCadastrar))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jLabel8)
              .addComponent(jLabel3)
              .addComponent(jLabel4)
              .addComponent(jLabel5)
              .addComponent(jLabel6)
              .addComponent(jLabel7)
              .addComponent(txtUsername)
              .addComponent(txtEmail)
              .addComponent(txtBiografia)
              .addComponent(txtNome)
              .addComponent(cmbTipoUsuario, 0, 406, Short.MAX_VALUE)
              .addComponent(txtSenha))))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(26, 26, 26)
        .addComponent(jLabel2)
        .addGap(18, 18, 18)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel4)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel5)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel6)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jLabel7)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtBiografia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel8)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(cmbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnCadastrar)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1))
          .addGroup(layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(38, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(20, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
    try{
      
      if (txtNome.getText().isEmpty() ||txtUsername.getText().isEmpty() ||txtSenha.getPassword().length == 0 ||txtSenha.getText().isEmpty() 
     || txtBiografia.getText().isEmpty() || cmbTipoUsuario.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "preencha todos os campos!");
        return;
      }
      
      Usuario novoUsuario = new Usuario();
      
      String senha = new String(txtSenha.getPassword());
      novoUsuario.setSenha(Criptografia.getMD5(senha));
      novoUsuario.setNome(txtNome.getText());
      novoUsuario.setUsername(txtUsername.getText());
      novoUsuario.setEmail(txtEmail.getText());
      novoUsuario.setBiografia(txtBiografia.getText());
      novoUsuario.setTipoUsuario(cmbTipoUsuario.getSelectedItem().toString());

      
      ListaUsuario listaUsuario = new ListaUsuario();
      listaUsuario.cadastrar(novoUsuario);
      JOptionPane.showMessageDialog(this, "usuário cadastrado com sucesso!" );
      this.dispose();
    }
    catch(Exception e){
      JOptionPane.showMessageDialog(this, "ocorreu uma falha:\n" + e.getMessage());
    }
  }//GEN-LAST:event_btnCadastrarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new CadastroUsuario().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCadastrar;
  private javax.swing.JComboBox<String> cmbTipoUsuario;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JTextField txtBiografia;
  private javax.swing.JTextField txtEmail;
  private javax.swing.JTextField txtNome;
  private javax.swing.JPasswordField txtSenha;
  private javax.swing.JTextField txtUsername;
  // End of variables declaration//GEN-END:variables

}
