/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import dados.Criptografia;
import dados.ListaUsuario;
import dados.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows 11
 */
public class TelaLogin extends javax.swing.JFrame {
  
  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaLogin.class.getName());

  /**
   * Creates new form TelaLogin
   */
  public TelaLogin() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
   * Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jPanel1 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    txtUsername = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();
    btnLogin = new javax.swing.JButton();
    btnCadastroUsuario = new javax.swing.JButton();
    txtSenha = new javax.swing.JPasswordField();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setBackground(new java.awt.Color(204, 204, 204));
    jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(0, 51, 51));
    jLabel1.setText("entre laços & nós");

    jPanel1.setBackground(new java.awt.Color(0, 51, 51));
    jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 51), 2, true));
    jPanel1.setForeground(new java.awt.Color(0, 51, 51));

    jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 20)); // NOI18N
    jLabel2.setText("faça seu login!");

    txtUsername.setBackground(new java.awt.Color(204, 204, 204));

    jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
    jLabel3.setText("username:");

    jLabel6.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
    jLabel6.setText("senha:");

    btnLogin.setBackground(new java.awt.Color(204, 204, 204));
    btnLogin.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
    btnLogin.setForeground(new java.awt.Color(0, 51, 51));
    btnLogin.setText("login");
    btnLogin.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLoginActionPerformed(evt);
      }
    });

    btnCadastroUsuario.setBackground(new java.awt.Color(0, 51, 51));
    btnCadastroUsuario.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
    btnCadastroUsuario.setText("crie uma conta!");
    btnCadastroUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
    btnCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCadastroUsuarioActionPerformed(evt);
      }
    });

    txtSenha.setBackground(new java.awt.Color(204, 204, 204));
    txtSenha.setForeground(new java.awt.Color(0, 51, 51));

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
        .addContainerGap(156, Short.MAX_VALUE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addComponent(btnLogin)
            .addGap(172, 172, 172))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addGap(144, 144, 144))))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(txtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
          .addComponent(jLabel3)
          .addComponent(btnCadastroUsuario, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jLabel6)
          .addComponent(txtSenha))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(42, 42, 42)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(4, 4, 4)
        .addComponent(jLabel6)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(btnLogin)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
        .addComponent(btnCadastroUsuario)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel1))
          .addGroup(layout.createSequentialGroup()
            .addGap(30, 30, 30)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(31, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(20, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
   
    if (txtUsername.getText().trim().isEmpty() ||txtSenha.getPassword().length == 0 ) {
      JOptionPane.showMessageDialog(null, "preencha todos os campos");
      return;
    }
    
    Usuario usuario = new Usuario();
    
    String senha = new String(txtSenha.getPassword());
    usuario.setSenha(Criptografia.getMD5(senha));
    usuario.setUsername(txtUsername.getText());
    
    usuario = ListaUsuario.validarUsuario(usuario);
   
    if (usuario != null && usuario.getTipoUsuario() != null) {
      Sessao.tipoUsuario = usuario.getTipoUsuario();
      
      if( usuario.getTipoUsuario().equalsIgnoreCase("admin") ) {
        JOptionPane.showMessageDialog(null, "seja bem-vindo(a) ao entre laços & nós! \nsua conta é do tipo: admin");
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        telaPrincipal.setVisible(true);
      }
      else if ( usuario.getTipoUsuario().equalsIgnoreCase("usuário") ) {
        JOptionPane.showMessageDialog(null, "seja bem-vindo(a) ao entre laços & nós! \nsua conta é do tipo: usuário");
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        telaPrincipal.configurarPermissoes();
        telaPrincipal.setVisible(true);
        
      }
      else if ( usuario.getTipoUsuario().equalsIgnoreCase("visitante") ) {
        JOptionPane.showMessageDialog(null, "seja bem-vindo(a) ao entre laços & nós! \nsua conta é do tipo: visitante");
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        telaPrincipal.configurarPermissoes();
        telaPrincipal.setVisible(true);
      }
      else {
        JOptionPane.showMessageDialog(null, "ops, parece que você não tem uma conta, crie uma e tente novamente! ");
        txtUsername.setText("");
        txtSenha.setText(null);
      }
    }
    else {
      JOptionPane.showMessageDialog(null, "erro de autenticação! verifique se os dados estão corretos.");
      txtUsername.setText("");
      txtSenha.setText(null);
    }
  }//GEN-LAST:event_btnLoginActionPerformed

  private void btnCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroUsuarioActionPerformed
    CadastroUsuario usuario = new CadastroUsuario();
    usuario.setVisible(true);
  }//GEN-LAST:event_btnCadastroUsuarioActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new TelaLogin().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnCadastroUsuario;
  private javax.swing.JButton btnLogin;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPasswordField txtSenha;
  private javax.swing.JTextField txtUsername;
  // End of variables declaration//GEN-END:variables
}
