/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import dados.ListaProjeto;
import dados.ListaReceita;
import dados.Projeto;
import dados.Receita;
import java.awt.CardLayout;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Windows 11
 */
public class TelaPrincipal extends javax.swing.JFrame {
  
  private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

  /**
   * Creates new form TelaInicial
   */
  public TelaPrincipal() {
    initComponents();
    configurarPermissoes();
    
    
    pnlPrincipal.add(pnlHome, "home");
    pnlPrincipal.add(pnlProjetos, "projetos");
    pnlPrincipal.add(pnlReceitas, "receitas");
    CardLayout cl = (CardLayout) pnlPrincipal.getLayout();
    cl.show(pnlPrincipal, "home");
    
    
    atualizarTabelaProjetosHome();
    atualizarTabelaReceitasHome();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form
   * Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    pnlBotão = new javax.swing.JPanel();
    btnHome = new javax.swing.JButton();
    btnProjetos = new javax.swing.JButton();
    btnReceitas = new javax.swing.JButton();
    pnlTitulo = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    pnlFundo = new javax.swing.JPanel();
    pnlPrincipal = new javax.swing.JPanel();
    pnlHome = new javax.swing.JPanel();
    jscrlProjetosHome = new javax.swing.JScrollPane();
    tblProjetosHome = new javax.swing.JTable();
    jscrlReceitasHome = new javax.swing.JScrollPane();
    tblReceitasHome = new javax.swing.JTable();
    pnlProjetos = new javax.swing.JPanel();
    jscrlProjetos = new javax.swing.JScrollPane();
    tblProjetos = new javax.swing.JTable();
    btnExcluirProjetos = new javax.swing.JButton();
    btnCadastroProjetos = new javax.swing.JButton();
    btnAtualizarProjetos = new javax.swing.JButton();
    pnlReceitas = new javax.swing.JPanel();
    jscrlReceitas = new javax.swing.JScrollPane();
    tblReceitas = new javax.swing.JTable();
    btnExcluirReceitas = new javax.swing.JButton();
    btnCadastroReceitas = new javax.swing.JButton();
    btnAtualizarReceitas = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setBackground(new java.awt.Color(0, 51, 51));

    pnlBotão.setBackground(new java.awt.Color(0, 51, 51));
    pnlBotão.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
    pnlBotão.setForeground(new java.awt.Color(0, 51, 51));

    btnHome.setBackground(new java.awt.Color(204, 204, 204));
    btnHome.setFont(new java.awt.Font("Segoe Print", 0, 20)); // NOI18N
    btnHome.setForeground(new java.awt.Color(0, 51, 51));
    btnHome.setText("home");
    btnHome.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnHomeActionPerformed(evt);
      }
    });

    btnProjetos.setBackground(new java.awt.Color(204, 204, 204));
    btnProjetos.setFont(new java.awt.Font("Segoe Print", 0, 20)); // NOI18N
    btnProjetos.setForeground(new java.awt.Color(0, 51, 51));
    btnProjetos.setText("projetos");
    btnProjetos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnProjetosActionPerformed(evt);
      }
    });

    btnReceitas.setBackground(new java.awt.Color(204, 204, 204));
    btnReceitas.setFont(new java.awt.Font("Segoe Print", 0, 20)); // NOI18N
    btnReceitas.setForeground(new java.awt.Color(0, 51, 51));
    btnReceitas.setText("receitas");
    btnReceitas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnReceitasActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pnlBotãoLayout = new javax.swing.GroupLayout(pnlBotão);
    pnlBotão.setLayout(pnlBotãoLayout);
    pnlBotãoLayout.setHorizontalGroup(
      pnlBotãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlBotãoLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlBotãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnReceitas)
          .addComponent(btnProjetos)
          .addComponent(btnHome))
        .addContainerGap(14, Short.MAX_VALUE))
    );
    pnlBotãoLayout.setVerticalGroup(
      pnlBotãoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlBotãoLayout.createSequentialGroup()
        .addGap(52, 52, 52)
        .addComponent(btnHome)
        .addGap(83, 83, 83)
        .addComponent(btnProjetos)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnReceitas)
        .addGap(52, 52, 52))
    );

    pnlTitulo.setBackground(new java.awt.Color(0, 51, 51));
    pnlTitulo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
    pnlTitulo.setForeground(new java.awt.Color(0, 51, 51));

    jLabel1.setBackground(new java.awt.Color(204, 204, 204));
    jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 36)); // NOI18N
    jLabel1.setText("entre laços e nós");

    javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
    pnlTitulo.setLayout(pnlTituloLayout);
    pnlTituloLayout.setHorizontalGroup(
      pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel1)
        .addGap(216, 216, 216))
    );
    pnlTituloLayout.setVerticalGroup(
      pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pnlFundo.setBackground(new java.awt.Color(0, 51, 51));
    pnlFundo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

    pnlPrincipal.setBackground(new java.awt.Color(0, 51, 51));
    pnlPrincipal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
    pnlPrincipal.setLayout(new java.awt.CardLayout());

    pnlHome.setBackground(new java.awt.Color(0, 51, 51));
    pnlHome.setForeground(new java.awt.Color(0, 51, 51));

    jscrlProjetosHome.setBackground(new java.awt.Color(0, 51, 51));
    jscrlProjetosHome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "projetos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 12))); // NOI18N

    tblProjetosHome.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "id", "nome", "categoria", "duração", "material", "status", "usuário", "id receita"
      }
    ));
    jscrlProjetosHome.setViewportView(tblProjetosHome);

    jscrlReceitasHome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "receitas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 12))); // NOI18N

    tblReceitasHome.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "id", "nome", "categoria", "dificuldade", "material", "conteúdo", "usuário"
      }
    ));
    jscrlReceitasHome.setViewportView(tblReceitasHome);

    javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
    pnlHome.setLayout(pnlHomeLayout);
    pnlHomeLayout.setHorizontalGroup(
      pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlHomeLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jscrlProjetosHome, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
          .addComponent(jscrlReceitasHome))
        .addContainerGap())
    );
    pnlHomeLayout.setVerticalGroup(
      pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlHomeLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jscrlProjetosHome, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jscrlReceitasHome, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(16, 16, 16))
    );

    pnlPrincipal.add(pnlHome, "card2");

    pnlProjetos.setBackground(new java.awt.Color(0, 51, 51));
    pnlProjetos.setForeground(new java.awt.Color(0, 51, 51));

    jscrlProjetos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "projetos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 12))); // NOI18N

    tblProjetos.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null},
        {null, null, null, null, null, null, null, null}
      },
      new String [] {
        "id", "nome", "categoria", "duração", "material", "status", "usuário", "id receita"
      }
    ));
    jscrlProjetos.setViewportView(tblProjetos);

    btnExcluirProjetos.setBackground(new java.awt.Color(204, 204, 204));
    btnExcluirProjetos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    btnExcluirProjetos.setForeground(new java.awt.Color(153, 0, 0));
    btnExcluirProjetos.setText("x");
    btnExcluirProjetos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnExcluirProjetosActionPerformed(evt);
      }
    });

    btnCadastroProjetos.setBackground(new java.awt.Color(204, 204, 204));
    btnCadastroProjetos.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    btnCadastroProjetos.setForeground(new java.awt.Color(0, 51, 51));
    btnCadastroProjetos.setText("+");
    btnCadastroProjetos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCadastroProjetosActionPerformed(evt);
      }
    });

    btnAtualizarProjetos.setBackground(new java.awt.Color(204, 204, 204));
    btnAtualizarProjetos.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
    btnAtualizarProjetos.setForeground(new java.awt.Color(193, 155, 0));
    btnAtualizarProjetos.setText("↻");
    btnAtualizarProjetos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAtualizarProjetosActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pnlProjetosLayout = new javax.swing.GroupLayout(pnlProjetos);
    pnlProjetos.setLayout(pnlProjetosLayout);
    pnlProjetosLayout.setHorizontalGroup(
      pnlProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlProjetosLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jscrlProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(pnlProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExcluirProjetos, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(btnAtualizarProjetos))
          .addComponent(btnCadastroProjetos, javax.swing.GroupLayout.Alignment.TRAILING))
        .addContainerGap())
    );
    pnlProjetosLayout.setVerticalGroup(
      pnlProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlProjetosLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlProjetosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jscrlProjetos, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
          .addGroup(pnlProjetosLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(btnAtualizarProjetos)
            .addGap(18, 18, 18)
            .addComponent(btnCadastroProjetos)
            .addGap(18, 18, 18)
            .addComponent(btnExcluirProjetos)))
        .addContainerGap())
    );

    pnlPrincipal.add(pnlProjetos, "card3");

    pnlReceitas.setBackground(new java.awt.Color(0, 51, 51));
    pnlReceitas.setForeground(new java.awt.Color(0, 51, 51));

    jscrlReceitas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "receitas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe Print", 0, 12))); // NOI18N

    tblReceitas.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "id", "nome", "categoria", "conteúdo", "material", "dificuldade", "usuário"
      }
    ));
    jscrlReceitas.setViewportView(tblReceitas);

    btnExcluirReceitas.setBackground(new java.awt.Color(204, 204, 204));
    btnExcluirReceitas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    btnExcluirReceitas.setForeground(new java.awt.Color(153, 0, 0));
    btnExcluirReceitas.setText("x");
    btnExcluirReceitas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnExcluirReceitasActionPerformed(evt);
      }
    });

    btnCadastroReceitas.setBackground(new java.awt.Color(204, 204, 204));
    btnCadastroReceitas.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
    btnCadastroReceitas.setForeground(new java.awt.Color(0, 51, 51));
    btnCadastroReceitas.setText("+");
    btnCadastroReceitas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnCadastroReceitasActionPerformed(evt);
      }
    });

    btnAtualizarReceitas.setBackground(new java.awt.Color(204, 204, 204));
    btnAtualizarReceitas.setFont(new java.awt.Font("Segoe UI Symbol", 0, 24)); // NOI18N
    btnAtualizarReceitas.setForeground(new java.awt.Color(193, 155, 0));
    btnAtualizarReceitas.setText("↻");
    btnAtualizarReceitas.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAtualizarReceitasActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout pnlReceitasLayout = new javax.swing.GroupLayout(pnlReceitas);
    pnlReceitas.setLayout(pnlReceitasLayout);
    pnlReceitasLayout.setHorizontalGroup(
      pnlReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlReceitasLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jscrlReceitas, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(pnlReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(pnlReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnExcluirReceitas)
            .addComponent(btnAtualizarReceitas, javax.swing.GroupLayout.Alignment.TRAILING))
          .addComponent(btnCadastroReceitas, javax.swing.GroupLayout.Alignment.TRAILING))
        .addContainerGap())
    );
    pnlReceitasLayout.setVerticalGroup(
      pnlReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReceitasLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(pnlReceitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jscrlReceitas, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
          .addGroup(pnlReceitasLayout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(btnAtualizarReceitas)
            .addGap(18, 18, 18)
            .addComponent(btnCadastroReceitas)
            .addGap(18, 18, 18)
            .addComponent(btnExcluirReceitas)))
        .addContainerGap())
    );

    pnlPrincipal.add(pnlReceitas, "card4");

    javax.swing.GroupLayout pnlFundoLayout = new javax.swing.GroupLayout(pnlFundo);
    pnlFundo.setLayout(pnlFundoLayout);
    pnlFundoLayout.setHorizontalGroup(
      pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlFundoLayout.createSequentialGroup()
        .addGap(20, 20, 20)
        .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    pnlFundoLayout.setVerticalGroup(
      pnlFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(pnlFundoLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(layout.createSequentialGroup()
            .addComponent(pnlBotão, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(pnlFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(pnlBotão, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProjetosActionPerformed
    atualizarTabelaProjetos();
    
    ((CardLayout)pnlPrincipal.getLayout()).show(pnlPrincipal, "projetos");
  }//GEN-LAST:event_btnProjetosActionPerformed

  private void btnReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceitasActionPerformed
    atualizarTabelaReceitas();
    
    ((CardLayout)pnlPrincipal.getLayout()).show(pnlPrincipal, "receitas");
  }//GEN-LAST:event_btnReceitasActionPerformed

  private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
    ((CardLayout)pnlPrincipal.getLayout()).show(pnlPrincipal, "home");
    atualizarTabelaProjetosHome();
    atualizarTabelaReceitasHome();
  }//GEN-LAST:event_btnHomeActionPerformed

  private void btnExcluirProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProjetosActionPerformed
   try{
      
      if(tblProjetos.getSelectedRow() >= 0){String id = (String)tblProjetos.getValueAt(tblProjetos.getSelectedRow(), 0);
       int resposta = JOptionPane.showConfirmDialog(this, "deseja mesmo excluir o projeto " + id + "?");
       
       if(resposta == 0){
         ListaProjeto listaProjetos = new ListaProjeto();
         listaProjetos.excluir(Integer.parseInt(id));
         JOptionPane. showMessageDialog(this, "projeto excluído com sucesso!");
         atualizarTabelaProjetos();

       }
      }
    }
    catch(Exception e){
      JOptionPane.showMessageDialog(this, "ocorreu um erro!\n Verifique os dados e tente novamente!");
      System.out.println(e.getMessage());
    }
  }//GEN-LAST:event_btnExcluirProjetosActionPerformed

  private void btnExcluirReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirReceitasActionPerformed
    try{
      
      if(tblReceitas.getSelectedRow() >= 0){String id = (String)tblReceitas.getValueAt(tblReceitas.getSelectedRow(), 0);
       int resposta = JOptionPane.showConfirmDialog(this, "deseja mesmo excluir a receita " + id + "?");
       
       if(resposta == 0){
         ListaReceita listaReceita = new ListaReceita();
         listaReceita.excluir(Integer.parseInt(id));
         JOptionPane. showMessageDialog(this, "receita excluída com sucesso!");
         atualizarTabelaReceitas();

       }
      }
    }
    catch(Exception e){
      JOptionPane.showMessageDialog(this, "ocorreu um erro!\n Verifique os dados e tente novamente!");
      System.out.println(e.getMessage());
    }
  }//GEN-LAST:event_btnExcluirReceitasActionPerformed

  private void btnCadastroReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroReceitasActionPerformed
    CadastroReceita receita = new CadastroReceita();
    atualizarTabelaReceitas();
    receita.setVisible(true);
  }//GEN-LAST:event_btnCadastroReceitasActionPerformed

  private void btnCadastroProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroProjetosActionPerformed
    CadastroProjeto projeto = new CadastroProjeto();
    atualizarTabelaProjetos();
    projeto.setVisible(true);
  }//GEN-LAST:event_btnCadastroProjetosActionPerformed

  private void btnAtualizarProjetosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarProjetosActionPerformed
    atualizarTabelaProjetos();  }//GEN-LAST:event_btnAtualizarProjetosActionPerformed

  private void btnAtualizarReceitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarReceitasActionPerformed
    atualizarTabelaReceitas();
  }//GEN-LAST:event_btnAtualizarReceitasActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
      logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAtualizarProjetos;
  private javax.swing.JButton btnAtualizarReceitas;
  private javax.swing.JButton btnCadastroProjetos;
  private javax.swing.JButton btnCadastroReceitas;
  private javax.swing.JButton btnExcluirProjetos;
  private javax.swing.JButton btnExcluirReceitas;
  private javax.swing.JButton btnHome;
  private javax.swing.JButton btnProjetos;
  private javax.swing.JButton btnReceitas;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jscrlProjetos;
  private javax.swing.JScrollPane jscrlProjetosHome;
  private javax.swing.JScrollPane jscrlReceitas;
  private javax.swing.JScrollPane jscrlReceitasHome;
  private javax.swing.JPanel pnlBotão;
  private javax.swing.JPanel pnlFundo;
  private javax.swing.JPanel pnlHome;
  private javax.swing.JPanel pnlPrincipal;
  private javax.swing.JPanel pnlProjetos;
  private javax.swing.JPanel pnlReceitas;
  private javax.swing.JPanel pnlTitulo;
  private javax.swing.JTable tblProjetos;
  private javax.swing.JTable tblProjetosHome;
  private javax.swing.JTable tblReceitas;
  private javax.swing.JTable tblReceitasHome;
  // End of variables declaration//GEN-END:variables
 
  private void preencheTabelaProjetosHome(List<Projeto> projeto){
    String columns[] = {"id","nome", "categoria", "duração", "material", "status", "usuário", "id receita"};
    String dados[][] = new String[projeto.size()][columns.length];
    
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
    
    int i=0;
    for(Projeto d: projeto){
      dados[i] = new String[]{
        
        String.valueOf(d.getId_projeto()),
        d.getNome(),
        d.getCategoria(),
        d.getDuracao().format(formatter),
        d.getMaterial(),
        d.getStatus(),
        d.getUsuario().getUsername(),
        String.valueOf(d.getReceita().getId_receita())};
      i++;
    }
    DefaultTableModel model = new DefaultTableModel(dados, columns);
    tblProjetosHome.setModel(model);
  }  
  private void atualizarTabelaProjetosHome() {
    ListaProjeto listaProjeto = new ListaProjeto();
    List<Projeto> projetos = listaProjeto.listar();
    preencheTabelaProjetosHome(projetos);
  }
  
  private void preencheTabelaProjetos(List<Projeto> projeto){
   String columns[] = {"id","nome", "categoria", "duração", "material", "status", "usuário", "id receita"};
    String dados[][] = new String[projeto.size()][columns.length];
    
    DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm:ss");
    
    int i=0;
    for(Projeto d: projeto){
      dados[i] = new String[]{
        
        String.valueOf(d.getId_projeto()),
        d.getNome(),
        d.getCategoria(),
        d.getDuracao().format(formatter),
        d.getMaterial(),
        d.getStatus(),
        d.getUsuario().getUsername(),
        String.valueOf(d.getReceita().getId_receita())};
      i++;
    }
    DefaultTableModel model = new DefaultTableModel(dados, columns);
    tblProjetos.setModel(model);
  } 
  private void atualizarTabelaProjetos() {
    ListaProjeto listaProjeto = new ListaProjeto();
    List<Projeto> projetos = listaProjeto.listar();
    preencheTabelaProjetos(projetos);
  }
  
  private void preencheTabelaReceitasHome(List<Receita> receita){
    String columns[] = {"id","nome", "categoria", "dificuldade", "material", "conteúdo","usuário"};
    String dados[][] = new String[receita.size()][columns.length];
    
    int i=0;
    for(Receita d: receita){
      dados[i] = new String[]{
        
        String.valueOf(d.getId_receita()),
        d.getNome(),
        d.getCategoria(),
        d.getDificuldade(),
        d.getMaterial(),
        d.getConteudo(),
        d.getUsuario().getUsername()};
      i++;
    }
    DefaultTableModel model = new DefaultTableModel(dados, columns);
    tblReceitasHome.setModel(model);
  } 
  private void atualizarTabelaReceitasHome() {
    ListaReceita listaReceita = new ListaReceita();
    List<Receita> receitas = listaReceita.listar();
    preencheTabelaReceitasHome(receitas);
  }
  
  private void preencheTabelaReceitas(List<Receita> receita){
    String columns[] = {"id","nome", "categoria", "dificuldade", "material", "conteúdo","usuário"};
    String dados[][] = new String[receita.size()][columns.length];
    
    int i=0;
    for(Receita d: receita){
      dados[i] = new String[]{
        
        String.valueOf(d.getId_receita()),
        d.getNome(),
        d.getCategoria(),
        d.getDificuldade(),
        d.getMaterial(),
        d.getConteudo(),
        d.getUsuario().getUsername()};
      i++;
    }
    DefaultTableModel model = new DefaultTableModel(dados, columns);
    tblReceitas.setModel(model);
  } 
  private void atualizarTabelaReceitas() {
    ListaReceita listaReceita = new ListaReceita();
    List<Receita> receitas = listaReceita.listar();
    preencheTabelaReceitas(receitas);
  }
  
  public void configurarPermissoes(){
    if (Sessao.tipoUsuario.equalsIgnoreCase("usuário")) {
        btnExcluirProjetos.setEnabled(false);
        btnExcluirReceitas.setEnabled(false);
    }
    if (Sessao.tipoUsuario.equalsIgnoreCase("visitante")) {
        btnExcluirReceitas.setEnabled(false);
        btnExcluirProjetos.setEnabled(false);
        btnExcluirProjetos.setEnabled(false);
        btnExcluirReceitas.setEnabled(false);
    }
  }

}
